---
# tasks file for easy_rsa (CentOS specific)

- name: Install EPEL repo
  become: yes
  yum:
    name: epel-release
    state: present

- name: Install easy-rsa package
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ easy_rsa_packages }}"
  tags:
    - easy_rsa
